import Navbar from './_components/Navbar'
import Sidebar from './_components/Sidebar'
import './globals.css'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'StockSheet',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className='bg-slate-900 overscroll-contain overflow-x-hidden'>
        <div className='relative flex w-full'>
          <div className='fixed top-0 left-0 max-w-[15%] w-[15%] overflow-y-hidden'>
            <Sidebar/>
          </div>
  
          <div className='max-w-[85%] w-[85%] absolute left-[15%]'>
            <Navbar/>
            {children}
          </div>
        </div>
        <Toaster position='top-right'/>
      </body>
    </html>
  )
}
